#!/usr/bin/env python3
"""Export scaler statistics to a C++ header."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import joblib


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCALER_PATH = PROJECT_ROOT / \
    "datasets" / "train_test_split" / "scaler.pkl"
DEFAULT_HEADER_PATH = PROJECT_ROOT / "include" / "scaler.h"


def load_mean_std(scaler_path: Path) -> tuple[np.ndarray, np.ndarray]:

    scaler = joblib.load(scaler_path)

    return np.asarray(scaler.mean_, dtype=np.float32), np.asarray(scaler.scale_, dtype=np.float32)


def _to_cpp_float_array(values: np.ndarray) -> str:
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    formatted = ", ".join(f"{float(v):.9g}f" for v in flat)
    return "{" + formatted + "}"


def write_header(output_header: Path, mean: np.ndarray, std: np.ndarray) -> None:
    mean_flat = np.asarray(mean, dtype=np.float32).reshape(-1)
    std_flat = np.asarray(std, dtype=np.float32).reshape(-1)

    header_text = (
        "#pragma once\n\n"
        "// Auto-generated by python/convert_scaler_to_carray.py.\n"
        "#include <cstdint>\n\n"
        f"inline constexpr uint8_t kScalerFeatureCount = {mean_flat.size};\n"
        "inline constexpr float kScalerMean[] = "
        f"{_to_cpp_float_array(mean_flat)};\n"
        "inline constexpr float kScalerStd[] = "
        f"{_to_cpp_float_array(std_flat)};\n"
    )

    output_header.parent.mkdir(parents=True, exist_ok=True)
    output_header.write_text(header_text, encoding="ascii")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read datasets/train_test_split/scaler.pkl and write scaler mean/std "
            "to include/scaler.h as inline constexpr float values."
        )
    )
    parser.add_argument(
        "--scaler",
        type=Path,
        default=DEFAULT_SCALER_PATH,
        help="Path to scaler pickle file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_HEADER_PATH,
        help="Path to generated C++ header file.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    scaler_path = args.scaler.resolve()
    output_path = args.output.resolve()

    mean, std = load_mean_std(scaler_path)
    write_header(output_path, mean, std)

    print(f"Wrote scaler header to: {output_path}")
    print(f"kScalerFeatureCount={mean.size}")


if __name__ == "__main__":
    main()
