#!/usr/bin/env python3
"""Export error threshold to a C++ header."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import joblib


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_THRESHOLD_PATH = PROJECT_ROOT / "model" / "error_threshold.pkl"
DEFAULT_HEADER_PATH = PROJECT_ROOT / "include" / "error_threshold.h"


def write_header(threshold: np.float32) -> None:
    header_text = (
        "#pragma once\n\n"
        "// Auto-generated by python/convert_threshold_to_c.py.\n"
        f"inline constexpr float kErrorThreshold = {threshold};\n"
    )

    DEFAULT_HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_HEADER_PATH.write_text(header_text, encoding="ascii")


if __name__ == "__main__":
    err_t = joblib.load(DEFAULT_THRESHOLD_PATH)
    write_header(err_t)
