from __future__ import annotations

from pathlib import Path

import numpy as np

from paths import DATASETS_DIR, PROJECT_ROOT


SAMPLE_RATE_HZ = 48_000
STORED_SECONDS = 1
STORED_SAMPLES = SAMPLE_RATE_HZ * STORED_SECONDS
OUTPUT_DIR = PROJECT_ROOT / "lib" / "sensor_source"
HEADER_PATH = OUTPUT_DIR / "sensor_source_data.h"
SOURCE_PATH = OUTPUT_DIR / "sensor_source_data.cpp"


def load_signal(path: Path) -> np.ndarray:
    signal = np.load(path)
    signal = np.asarray(signal, dtype=np.float32).reshape(-1)
    if signal.size < STORED_SAMPLES:
        raise ValueError(
            f"Signal too short for {STORED_SAMPLES} samples: {path}")
    return np.ascontiguousarray(signal[:STORED_SAMPLES])


def to_i16(signal: np.ndarray, i16_scale: float) -> np.ndarray:
    scaled = np.clip(signal * i16_scale, -32768.0, 32767.0).astype(np.int16)
    return np.ascontiguousarray(scaled)


def format_float_literal(value: float) -> str:
    return np.format_float_scientific(value, precision=9, unique=False, trim="-") + "F"


def build_header(i16_scale: float) -> str:
    return "\n".join([
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "inline constexpr std::size_t kSensorStoredSamplesPerSignal = 48000U;",
        f"inline constexpr float kSensorI16Scale = {format_float_literal(i16_scale)};",
        "",
        "extern const int16_t kSensorNormalData[kSensorStoredSamplesPerSignal];",
        "extern const int16_t kSensorBallDefectData[kSensorStoredSamplesPerSignal];",
        "extern const int16_t kSensorInnerDefectData[kSensorStoredSamplesPerSignal];",
        "extern const int16_t kSensorOuterDefectData[kSensorStoredSamplesPerSignal];",
        "",
    ])


def build_source(signals: dict[str, np.ndarray], i16_scale: float) -> str:
    output_parts = [
        '#include "sensor_source_data.h"',
        "",
        "// Generated by python/convert_sensor_source_to_c.py.",
        "// Stores one second of each source signal, scaled globally to int16.",
        "",
    ]

    for name, signal in signals.items():
        output_parts.append(format_array(name, to_i16(signal, i16_scale)))
        output_parts.append("")

    return "\n".join(output_parts)


def format_array(name: str, values: np.ndarray) -> str:
    lines = [
        f"const int16_t {name}[kSensorStoredSamplesPerSignal] = {{"
    ]
    row = []
    for idx, value in enumerate(values):
        row.append(f"{int(value)}")
        if len(row) == 12:
            suffix = "," if idx != (len(values) - 1) else ""
            lines.append("    " + ", ".join(row) + suffix)
            row = []
    if row:
        lines.append("    " + ", ".join(row))
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    format_dir = DATASETS_DIR / "format"
    signals = {
        "kSensorNormalData": load_signal(format_dir / "normal_data.npy"),
        "kSensorBallDefectData": load_signal(format_dir / "ball_defect_data.npy"),
        "kSensorInnerDefectData": load_signal(format_dir / "inner_defect_data.npy"),
        "kSensorOuterDefectData": load_signal(format_dir / "outer_defect_data.npy"),
    }

    global_max_abs = max(float(np.max(np.abs(signal)))
                         for signal in signals.values())
    i16_scale = (32767.0 / global_max_abs) if global_max_abs > 0.0 else 1.0

    HEADER_PATH.write_text(build_header(i16_scale), encoding="ascii")
    SOURCE_PATH.write_text(build_source(signals, i16_scale), encoding="ascii")
    print(f"Wrote {HEADER_PATH}")
    print(f"Wrote {SOURCE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
