#pragma once

// Auto-generated by python/convert_scaler_to_carray.py.
#include <cstdint>

inline constexpr uint8_t kScalerFeatureCount = 9;
inline constexpr float kScalerMean[] = {0.0124781365f, 0.00423269719f, 0.0662180483f, 2.8914485f, 3.09636855f, 3.83916736f, 0.387631595f, -0.174374968f, 0.0455442332f};
inline constexpr float kScalerStd[] = {0.00284732273f, 0.00044832431f, 0.00341732684f, 0.214246616f, 0.274740458f, 0.360102892f, 0.0351661928f, 0.10577403f, 0.00244774041f};
